name: Build Kivy APK

on:
  push:
    branches: [ master ]   # поменяй на свою ветку, если нужно
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build APK with Buildozer action
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: '3.11'                # можно поменять
          buildozer-cmd: 'buildozer -v android debug'  # или release

      - name: Show bin folder (for debug)
        if: always()
        run: |
          echo "===== LS bin (recursive) ====="
          ls -laR bin || echo "bin not found"

      - name: Upload APK artifact (always run)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-apk
          path: |
            ./bin/**/*.apk
            ./bin/*.apk
